backend:
  name: test-repo # test-repo git-gateway
  accept_roles: # optional - accepts all users if left out
    - admin
    - editor
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img/artists
public_folder: img/artists
collections:
  - label: 'Artist'
    name: 'artist'
    create: true
    format: 'json'
    folder: 'assets/content/artists'
    slug: '{{slug}}'
    fields:
      - { label: 'DateAdded', name: 'dateAdded', widget: 'datetime' }
      - { label: 'LastUpdated', name: 'lastUpdate', widget: 'datetime' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Short Description (tl;dr)',
          name: 'shortDescription',
          widget: 'text'
        }
      - { label: 'Long Bio', name: 'longBio', widget: 'text', required: false }
      - {
          label: 'Work Examples',
          name: 'workExamples',
          widget: 'list',
          max: 10,
          min: 3,
          summary: '{{fields.image}}',
          field: { label: Image, name: image, widget: image }
        }
      - label: 'Contacts'
        name: 'contacts'
        widget: 'object'
        fields:
          - {
              label: 'Twitter',
              name: 'twitter',
              widget: 'string',
              required: false
            }
          - {
              label: 'Discord',
              name: 'discord',
              widget: 'string',
              required: false
            }
          - { label: 'Email', name: 'email', widget: 'string', required: false }
      - label: 'Work Cost'
        name: 'workCost'
        widget: 'object'
        fields:
          - {
              label: 'Preferred Currency',
              name: 'preferredCurrency',
              widget: 'select',
              options: ['USD', 'ETH']
            }
          - {
              label: 'When One Animation',
              name: 'whenOne',
              widget: 'number',
              value_type: 'float',
              min: 0,
              max: 100
            }
          - {
              label: 'When Batch Animations',
              name: 'whenBatch',
              widget: 'number',
              value_type: 'float',
              min: 0,
              max: 100,
              required: false
            }
          - {
              label: 'Comments',
              name: 'comments',
              widget: 'text',
              required: false
            }
